# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['theme']

# Cell
def theme():
    """Niklas Morberg's personal theme for Altair"""
    return {
        "config": {
            "axis": {
                "titleFontSize": 16,
                "labelFontSize": 12,
                "titleFont": "Avenir Next Medium, sans-serif",
            },
            "axisX": {"grid": False},
            "axisY": {"gridDash": [3], "gridWidth": 0.4},
            "legend": {
                "titleFontSize": 14,
                "titleFont": "Avenir Next Medium, sans-serif",
                "labelFontSize": 13,
            },
            "font": "Avenir Next, sans-serif",
            "title": {
                "anchor": "start",
                "frame": "group",
                "offset": 15,
                "fontSize": 20,
                "font": "Avenir Next Demi Bold",
            },
            "view": {"strokeWidth": 0, "continuousWidth": 600, "continuousHeight": 400},
        }
    }